log4j:
  appender:
    D: org.apache.log4j.DailyRollingFileAppender
      File: E://logs/log.log
      Append: True
      Threshold: DEBUG
      layout: org.apache.log4j.PatternLayout
        ConersionPattern: %-d{yyyy-MM-dd HH:mm:ss}  [ %t:%r ] - [ %p ]  %m%n
    E: org.apache.log4j.DailyRollingFileAppender
      File: E://logs/error.log
      Append: true
      Threshold: ERROR
      layout:
    stdout: org.apache.log4j.ConsoleAppender
      Target: System.out
        layout: org.apache.log4j.PatternLayout
          ConversionPattern: [%-5p] %d{yyyy-MM-dd HH:mm:ss,SSS} method:%l%n%m%n



